const Data = [
	{ id: 0, details: "even" },
	{ id: 1, details: "odd" },
	{ id: 2, details: "prime" },
	{ id: 3, details: "prime" },
	{ id: 4, details: "even" },
	{ id: 5, details: "prime" },
	{ id: 6, details: "even" },
	{ id: 7, details: "prime" },
	{ id: 8, details: "even" },
	{ id: 9, details: "odd" },
	{ id: 10, details: "even" },
	{ id: 11, details: "prime" },
	{ id: 12, details: "even" },
	{ id: 13, details: "prime" },
	{ id: 14, details: "even" },
	{ id: 15, details: "odd" },
	{ id: 16, details: "even" },
	{ id: 17, details: "prime" },
	{ id: 18, details: "even" },
	{ id: 19, details: "prime" },
	{ id: 20, details: "even" },
	{ id: 21, details: "odd" },
	{ id: 22, details: "even" },
	{ id: 23, details: "prime" },
	{ id: 24, details: "even" },
	{ id: 25, details: "odd" },
	{ id: 26, details: "even" },
	{ id: 27, details: "odd" },
	{ id: 28, details: "even" },
	{ id: 29, details: "prime" },
	{ id: 30, details: "even" },
	{ id: 31, details: "prime" },
];
export default Data;
